# Auto-generated by scripts.sanity_cleanup on 2025-10-21
set shell := ["bash", "-c"]

fpma-graph:
	@make fpma-graph

fpma-check:
	@make fpma-check

lock:
	@make lock

build-package:
	@make build-package

publish-package:
	@make publish-package

clean-dist:
	@make clean-dist

generate:
	@make generate

schema-validate:
	@make schema-validate

schema-catalog:
	@make schema-catalog

scripts-lint:
	@make scripts-lint

scripts-test:
	@make scripts-test

scripts-gen-proto:
	@make scripts-gen-proto

scripts-dev-up:
	@make scripts-dev-up

scripts-dev-down:
	@make scripts-dev-down

docs-lint:
	@make docs-lint

i18n-validate:
	@make i18n-validate

mutation-test:
	@make mutation-test

sbom:
	@make sbom

supply-chain-verify:
	@make supply-chain-verify

dependencies-check:
	@make dependencies-check

security-audit:
	@make security-audit
