apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - filebeat-rbac.yaml
  - filebeat-daemonset.yaml
  - logstash-deployment.yaml
  - logstash-service.yaml

configMapGenerator:
  - name: tradepulse-filebeat-config
    files:
      - filebeat.yml=config/filebeat.yml
  - name: tradepulse-logstash-pipeline
    files:
      - logstash.conf=config/logstash.conf

generatorOptions:
  disableNameSuffixHash: true
