# Copyright (c) 2023-2026 Yaroslav Vasylenko (neuron7xLab)
# SPDX-License-Identifier: MIT
"""The scan-toolchain gate (SEC-002) must have teeth.

Positive: the committed ``requirements-scan.lock`` pins ``pip-audit`` to an
exact hashed version -> gate exits 0.

Negative:
  * a scan manifest with ``pip-audit`` unpinned or ``pip-audit>=x`` -> non-zero;
  * ``pip-audit`` absent entirely -> non-zero;
  * an offline / errored run that *claims* GREEN -> flagged false-GREEN and
    classified RED (never a silent pass).
"""

from __future__ import annotations

from pathlib import Path

from scripts.ci.check_scan_toolchain import (
    GREEN,
    MANUAL,
    RED,
    ROOT,
    build_receipt,
    classify_scan_outcome,
    is_false_green,
    main,
    verify_scan_toolchain,
    verify_scan_toolchain_file,
)

_H1 = "a" * 64
_H2 = "b" * 64

# A minimal well-formed scan lock: pip-audit + pip exactly pinned and hashed.
GOOD_SCAN_LOCK = (
    "#\n"
    "# autogenerated by pip-compile\n"
    "#\n"
    f"pip-audit==2.10.1 \\\n"
    f"    --hash=sha256:{_H1} \\\n"
    f"    --hash=sha256:{_H2}\n"
    "# The following packages are considered to be unsafe in a requirements file:\n"
    f"pip==26.1.2 \\\n"
    f"    --hash=sha256:{_H1}\n"
)


# --------------------------------------------------------------------------- #
# POSITIVE                                                                     #
# --------------------------------------------------------------------------- #
def test_positive_pinned_hashed_pip_audit_passes() -> None:
    report = verify_scan_toolchain(GOOD_SCAN_LOCK, path="<good>")
    assert report.ok, report.errors
    assert report.pins["pip-audit"].is_exact
    assert report.pins["pip-audit"].is_hashed


def test_positive_committed_scan_lock_pins_pip_audit() -> None:
    """The real committed lock must pin+hash pip-audit (regression guard)."""
    report = verify_scan_toolchain_file(ROOT / "requirements-scan.lock")
    assert report.ok, report.errors
    pin = report.pins["pip-audit"]
    assert pin.is_exact and pin.is_hashed
    assert pin.version == "2.10.1"


def test_positive_main_exit_zero_on_good_lock(tmp_path: Path) -> None:
    lock = tmp_path / "requirements-scan.lock"
    lock.write_text(GOOD_SCAN_LOCK, encoding="utf-8")
    receipt = tmp_path / "receipt.json"
    assert main([str(lock), "--emit-receipt", str(receipt)]) == 0
    assert receipt.exists()
    assert "pip-audit" in receipt.read_text(encoding="utf-8")


# --------------------------------------------------------------------------- #
# NEGATIVE -- pinning                                                          #
# --------------------------------------------------------------------------- #
def test_negative_unpinned_pip_audit_fails() -> None:
    text = "pip-audit\n" f"pip==26.1.2 \\\n    --hash=sha256:{_H1}\n"
    report = verify_scan_toolchain(text)
    assert not report.ok
    assert any("pip-audit" in e and "pinned" in e for e in report.errors)


def test_negative_range_pip_audit_fails() -> None:
    text = "pip-audit>=2.0.0\n" f"pip==26.1.2 \\\n    --hash=sha256:{_H1}\n"
    report = verify_scan_toolchain(text)
    assert not report.ok
    assert any("pip-audit" in e for e in report.errors)


def test_negative_absent_pip_audit_fails() -> None:
    text = f"pip==26.1.2 \\\n    --hash=sha256:{_H1}\n"
    report = verify_scan_toolchain(text)
    assert not report.ok
    assert any("ABSENT" in e for e in report.errors)


def test_negative_pip_audit_without_hash_fails() -> None:
    text = "pip-audit==2.10.1\n" f"pip==26.1.2 \\\n    --hash=sha256:{_H1}\n"
    report = verify_scan_toolchain(text)
    assert not report.ok
    assert any("no --hash" in e for e in report.errors)


def test_negative_main_exit_nonzero_on_bad_lock(tmp_path: Path) -> None:
    lock = tmp_path / "requirements-scan.lock"
    lock.write_text("pip-audit>=2.0\n", encoding="utf-8")
    assert main([str(lock)]) == 1


# --------------------------------------------------------------------------- #
# NEGATIVE -- outcome honesty (no false GREEN)                                 #
# --------------------------------------------------------------------------- #
def test_offline_claiming_green_is_flagged_false_green() -> None:
    record: dict[str, object] = {
        "status": "GREEN",
        "online": False,
        "vulnerabilities_found": 0,
        "exit_code": 0,
    }
    assert is_false_green(record)
    assert classify_scan_outcome(record) == RED


def test_errored_run_is_red_not_green() -> None:
    record: dict[str, object] = {
        "status": "GREEN",
        "online": True,
        "error": "connection reset",
        "exit_code": 1,
        "vulnerabilities_found": 0,
    }
    assert classify_scan_outcome(record) == RED
    assert is_false_green(record)


def test_db_unreachable_is_red() -> None:
    record: dict[str, object] = {
        "online": True,
        "db_reachable": False,
        "exit_code": 0,
        "vulnerabilities_found": 0,
    }
    assert classify_scan_outcome(record) == RED


def test_missing_online_evidence_fails_closed() -> None:
    # No 'online' evidence at all -> cannot assert clean -> RED.
    record: dict[str, object] = {"exit_code": 0, "vulnerabilities_found": 0}
    assert classify_scan_outcome(record) == RED


def test_vulnerabilities_found_is_red() -> None:
    record: dict[str, object] = {
        "online": True,
        "exit_code": 0,
        "vulnerabilities_found": 3,
    }
    assert classify_scan_outcome(record) == RED


def test_genuine_clean_online_run_is_green() -> None:
    record: dict[str, object] = {
        "online": True,
        "db_reachable": True,
        "exit_code": 0,
        "vulnerabilities_found": 0,
    }
    assert classify_scan_outcome(record) == GREEN
    assert not is_false_green(record)


def test_requires_manual_degrades_to_manual() -> None:
    record: dict[str, object] = {"requires_manual": True, "status": "GREEN"}
    assert classify_scan_outcome(record) == MANUAL
    assert is_false_green(record)  # claimed GREEN, true verdict MANUAL


def test_receipt_records_version_and_digest() -> None:
    report = verify_scan_toolchain(GOOD_SCAN_LOCK)
    receipt = build_receipt(report)
    assert receipt["requirement"] == "SEC-002"
    assert receipt["pinned_tools"]["pip-audit"]["version"] == "2.10.1"
    assert receipt["pinned_tools"]["pip-audit"]["sha256"]
