# Copyright (c) 2023-2026 Yaroslav Vasylenko (neuron7xLab)
# SPDX-License-Identifier: MIT
"""The dependency-lock hash gate (ENV-003) must have teeth.

Positive: a hash-locked, exactly-pinned fixture line passes.
Negative: a line with no ``--hash`` -> gate non-zero; an unpinned ``name>=x``
-> gate non-zero. Also verifies the committed ``requirements*.lock`` files are
fully hashed so a regression that drops hashes is caught in CI.
"""

from __future__ import annotations

from pathlib import Path

from scripts.ci.check_lock_hashes import (
    DEFAULT_LOCKS,
    ROOT,
    build_provenance,
    main,
    verify_lock,
)

# A minimal, well-formed pip-compile --generate-hashes fixture (two requirements).
_H1 = "a" * 64
_H2 = "b" * 64
_H3 = "c" * 64
GOOD_LOCK = (
    "#\n"
    "# This file is autogenerated by pip-compile with Python 3.12\n"
    "#\n"
    f"numpy==2.3.3 \\\n"
    f"    --hash=sha256:{_H1} \\\n"
    f"    --hash=sha256:{_H2}\n"
    f"scipy==1.16.2 \\\n"
    f"    --hash=sha256:{_H3}\n"
)


# --------------------------------------------------------------------------- #
# POSITIVE                                                                     #
# --------------------------------------------------------------------------- #
def test_positive_hash_locked_line_passes() -> None:
    report = verify_lock(GOOD_LOCK, path="<good>", min_requirements=2)
    assert report.ok, report.errors
    assert report.requirement_count == 2
    assert report.hashed_count == 2
    assert report.unhashed_count == 0
    assert report.unpinned_count == 0


def test_positive_extras_and_multiple_hashes_pass() -> None:
    text = (
        f"strawberry-graphql[fastapi]==0.319.0 \\\n"
        f"    --hash=sha256:{_H1} \\\n"
        f"    --hash=sha256:{_H2}\n"
    )
    report = verify_lock(text, min_requirements=1)
    assert report.ok, report.errors
    assert report.hashed_count == 1


# --------------------------------------------------------------------------- #
# NEGATIVE                                                                     #
# --------------------------------------------------------------------------- #
def test_negative_missing_hash_fails_closed() -> None:
    text = "numpy==2.3.3\n"  # pinned but NO --hash
    report = verify_lock(text, min_requirements=1)
    assert not report.ok
    assert report.unhashed_count == 1
    assert any("no --hash" in e for e in report.errors)


def test_negative_unpinned_requirement_fails_closed() -> None:
    text = (
        f"numpy>=2.3.3 \\\n"
        f"    --hash=sha256:{_H1}\n"  # hashed but NOT exact-pinned
    )
    report = verify_lock(text, min_requirements=1)
    assert not report.ok
    assert report.unpinned_count == 1
    assert any("unpinned" in e for e in report.errors)


def test_negative_operatorless_requirement_fails_closed() -> None:
    text = f"numpy \\\n    --hash=sha256:{_H1}\n"
    report = verify_lock(text, min_requirements=1)
    assert not report.ok
    assert report.unpinned_count == 1


def test_negative_malformed_hash_fails_closed() -> None:
    text = "numpy==2.3.3 \\\n    --hash=sha256:deadbeef\n"  # too short
    report = verify_lock(text, min_requirements=1)
    assert not report.ok
    assert report.malformed_hash_count >= 1
    assert report.unhashed_count == 1  # the short digest is not a valid hash


def test_negative_duplicate_requirement_fails_closed() -> None:
    text = (
        f"numpy==2.3.3 \\\n    --hash=sha256:{_H1}\n"
        f"numpy==2.4.0 \\\n    --hash=sha256:{_H2}\n"
    )
    report = verify_lock(text, min_requirements=1)
    assert not report.ok
    assert report.duplicate_count == 1


def test_negative_vacuous_lock_fails_closed() -> None:
    report = verify_lock("# only a comment\n", min_requirements=10)
    assert not report.ok
    assert any("vacuous" in e for e in report.errors)


def test_exempt_build_backend_not_required_to_hash() -> None:
    text = (
        f"numpy==2.3.3 \\\n    --hash=sha256:{_H1}\n"
        "setuptools==80.0.0\n"  # unsafe/build backend, no hash required
    )
    report = verify_lock(text, min_requirements=1)
    assert report.ok, report.errors
    assert "setuptools" in report.exempt_unhashed


# --------------------------------------------------------------------------- #
# CLI / exit code                                                             #
# --------------------------------------------------------------------------- #
def test_cli_exit_zero_on_good_committed_locks(tmp_path: Path) -> None:
    committed = [ROOT / name for name in DEFAULT_LOCKS]
    assert all(p.exists() for p in committed), "committed locks must exist"
    rc = main([str(p) for p in committed])
    assert rc == 0


def test_cli_exit_nonzero_on_bad_lock(tmp_path: Path) -> None:
    bad = tmp_path / "requirements-bad.lock"
    bad.write_text("requests>=2.0\n", encoding="utf-8")
    rc = main([str(bad), "--min-requirements", "1"])
    assert rc == 1


def test_cli_exit_nonzero_on_missing_lock(tmp_path: Path) -> None:
    rc = main([str(tmp_path / "does-not-exist.lock")])
    assert rc == 1


def test_committed_locks_are_fully_hashed_and_pinned() -> None:
    """Regression guard: every committed lock is 100% hashed and pinned."""
    for name in DEFAULT_LOCKS:
        report = verify_lock(
            (ROOT / name).read_text(encoding="utf-8"), path=name, min_requirements=10
        )
        assert report.ok, f"{name}: {report.errors[:3]}"
        assert report.unhashed_count == 0, name
        assert report.unpinned_count == 0, name


def test_provenance_reports_true_generator_tool() -> None:
    from scripts.ci.check_lock_hashes import verify_lock_file

    reports = [verify_lock_file(ROOT / name) for name in DEFAULT_LOCKS]
    prov = build_provenance(reports)
    assert prov["gate_id"] == "G-LOCK-HASHES"
    for lock in prov["locks"]:
        assert lock["fully_hashed"] is True, lock["path"]
        assert lock["tool"].startswith("pip-compile"), lock["tool"]
