"""Unified domain model for TradePulse trading system.

This module provides the canonical domain entities used across all layers
of the TradePulse system: backtest, paper trading, and live execution.
All modules should use these types to ensure consistency and type safety.

Core Entities:
    - OrderRequest: Request to create a new order
    - OrderExecution: Represents an executed order fill
    - Trade: Completed trade with full execution details
    - PositionState: Current state of a position
    - PortfolioState: Snapshot of portfolio state
    - StrategySignal: Signal generated by a strategy
    - StrategyContext: Context passed to strategy for decision making
    - ActionDecision: Decision about what action to take
    - AAREvent: Acceptor of Action Result event for feedback loop

Type Aliases:
    - OrderId, StrategyId, TradeId, SignalId: Strongly-typed string IDs

See docs/DOMAIN_MODEL.md for full specification.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from enum import Enum
from types import MappingProxyType
from typing import Any, Mapping, NewType

# -----------------------------------------------------------------------------
# Strongly-typed ID aliases
# -----------------------------------------------------------------------------

OrderId = NewType("OrderId", str)
StrategyId = NewType("StrategyId", str)
TradeId = NewType("TradeId", str)
SignalId = NewType("SignalId", str)
PositionId = NewType("PositionId", str)


def generate_order_id() -> OrderId:
    """Generate a unique order ID."""
    return OrderId(f"ord_{uuid.uuid4().hex[:16]}")


def generate_trade_id() -> TradeId:
    """Generate a unique trade ID."""
    return TradeId(f"trd_{uuid.uuid4().hex[:16]}")


def generate_signal_id() -> SignalId:
    """Generate a unique signal ID."""
    return SignalId(f"sig_{uuid.uuid4().hex[:16]}")


# -----------------------------------------------------------------------------
# Enums for domain value objects
# -----------------------------------------------------------------------------


class EnvironmentMode(str, Enum):
    """Operational environment mode."""

    BACKTEST = "backtest"
    PAPER = "paper"
    LIVE = "live"


class ActionType(str, Enum):
    """Types of actions the system can decide to take."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE = "close"
    REDUCE = "reduce"
    SCALE_IN = "scale_in"
    SCALE_OUT = "scale_out"
    CANCEL = "cancel"


class SignalDirection(str, Enum):
    """Direction of a trading signal."""

    LONG = "long"
    SHORT = "short"
    FLAT = "flat"


class OrderRequestType(str, Enum):
    """Type of order request."""

    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"


class ExecutionStatus(str, Enum):
    """Status of order execution."""

    PENDING = "pending"
    SUBMITTED = "submitted"
    PARTIAL = "partial"
    FILLED = "filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"
    EXPIRED = "expired"


# -----------------------------------------------------------------------------
# Helper functions
# -----------------------------------------------------------------------------


def _freeze_mapping(mapping: Mapping[str, Any] | None) -> Mapping[str, Any]:
    """Return an immutable view over mapping."""
    if mapping is None:
        return MappingProxyType({})
    if isinstance(mapping, MappingProxyType):
        return mapping
    return MappingProxyType(dict(mapping))


def _utc_now() -> datetime:
    """Return current UTC datetime."""
    return datetime.now(timezone.utc)


def _ensure_utc(dt: datetime) -> datetime:
    """Ensure datetime has UTC timezone."""
    if dt.tzinfo is None:
        return dt.replace(tzinfo=timezone.utc)
    return dt


# -----------------------------------------------------------------------------
# Order Request & Execution
# -----------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class OrderRequest:
    """Request to create a new order.

    This represents the intent to place an order before it is submitted
    to the execution layer. Immutable to ensure request integrity.

    Attributes:
        symbol: Instrument symbol (e.g., "BTCUSD").
        side: Order side ("buy" or "sell").
        quantity: Order quantity. Must be positive.
        order_type: Type of order (market, limit, etc.).
        price: Limit price (required for limit orders).
        stop_price: Stop trigger price (for stop orders).
        strategy_id: ID of strategy that generated this request.
        signal_id: ID of signal that triggered this order.
        metadata: Additional order metadata.
        created_at: Timestamp when request was created.

    Raises:
        ValueError: If quantity is not positive or if limit order has no price.
    """

    symbol: str
    side: ActionType
    quantity: float
    order_type: OrderRequestType = OrderRequestType.MARKET
    price: float | None = None
    stop_price: float | None = None
    strategy_id: StrategyId | None = None
    signal_id: SignalId | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=_utc_now)

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError("quantity must be positive")
        if self.order_type == OrderRequestType.LIMIT and self.price is None:
            raise ValueError("limit orders require a price")
        if self.price is not None and self.price <= 0:
            raise ValueError("price must be positive when provided")
        if self.stop_price is not None and self.stop_price <= 0:
            raise ValueError("stop_price must be positive when provided")
        object.__setattr__(self, "metadata", _freeze_mapping(self.metadata))
        object.__setattr__(self, "created_at", _ensure_utc(self.created_at))


@dataclass(frozen=True, slots=True)
class OrderExecution:
    """Represents an executed order fill.

    Captures the details of a single fill event for an order. Multiple
    fills can occur for a single order (partial fills).

    Attributes:
        order_id: ID of the order being filled.
        symbol: Instrument symbol.
        side: Execution side.
        quantity: Filled quantity.
        price: Execution price.
        fee: Transaction fee.
        fee_currency: Currency of the fee.
        executed_at: Timestamp of execution.
        metadata: Additional execution metadata.

    Raises:
        ValueError: If quantity or price is not positive.
    """

    order_id: OrderId
    symbol: str
    side: ActionType
    quantity: float
    price: float
    fee: float = 0.0
    fee_currency: str = "USD"
    executed_at: datetime = field(default_factory=_utc_now)
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError("quantity must be positive")
        if self.price <= 0:
            raise ValueError("price must be positive")
        if self.fee < 0:
            raise ValueError("fee cannot be negative")
        object.__setattr__(self, "metadata", _freeze_mapping(self.metadata))
        object.__setattr__(self, "executed_at", _ensure_utc(self.executed_at))


@dataclass(frozen=True, slots=True)
class Trade:
    """Completed trade with full execution details.

    A Trade represents a completed round-trip or partial position change,
    aggregating one or more order executions.

    Attributes:
        trade_id: Unique trade identifier.
        symbol: Instrument symbol.
        side: Trade side.
        entry_price: Average entry price.
        exit_price: Average exit price (None if position still open).
        quantity: Trade quantity.
        realized_pnl: Realized profit/loss.
        fees: Total fees paid.
        opened_at: When the trade was opened.
        closed_at: When the trade was closed (None if still open).
        strategy_id: Strategy that initiated this trade.
        metadata: Additional trade metadata.

    Raises:
        ValueError: If quantity is not positive or prices are invalid.
    """

    trade_id: TradeId
    symbol: str
    side: ActionType
    entry_price: float
    quantity: float
    exit_price: float | None = None
    realized_pnl: float = 0.0
    fees: float = 0.0
    opened_at: datetime = field(default_factory=_utc_now)
    closed_at: datetime | None = None
    strategy_id: StrategyId | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError("quantity must be positive")
        if self.entry_price <= 0:
            raise ValueError("entry_price must be positive")
        if self.exit_price is not None and self.exit_price <= 0:
            raise ValueError("exit_price must be positive when provided")
        object.__setattr__(self, "metadata", _freeze_mapping(self.metadata))
        object.__setattr__(self, "opened_at", _ensure_utc(self.opened_at))
        if self.closed_at is not None:
            object.__setattr__(self, "closed_at", _ensure_utc(self.closed_at))

    @property
    def is_closed(self) -> bool:
        """Return True if trade is closed."""
        return self.exit_price is not None and self.closed_at is not None


# -----------------------------------------------------------------------------
# Position & Portfolio State
# -----------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class PositionState:
    """Current state of a position for a single instrument.

    Represents the current exposure and P&L for one symbol. Immutable
    snapshot that can be used safely across threads.

    Attributes:
        symbol: Instrument symbol.
        quantity: Position quantity (positive for long, negative for short).
        entry_price: Average entry price.
        current_price: Latest market price.
        unrealized_pnl: Current unrealized P&L.
        realized_pnl: Cumulative realized P&L.
        currency: Position currency.
        updated_at: Last update timestamp.

    Raises:
        ValueError: If entry_price or current_price is invalid.
    """

    symbol: str
    quantity: float = 0.0
    entry_price: float = 0.0
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    realized_pnl: float = 0.0
    currency: str = "USD"
    updated_at: datetime = field(default_factory=_utc_now)

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("symbol must be provided")
        if self.quantity != 0 and self.entry_price <= 0:
            raise ValueError("entry_price must be positive when position is open")
        if self.current_price < 0:
            raise ValueError("current_price cannot be negative")
        object.__setattr__(self, "updated_at", _ensure_utc(self.updated_at))

    @property
    def is_long(self) -> bool:
        """Return True if position is long."""
        return self.quantity > 0

    @property
    def is_short(self) -> bool:
        """Return True if position is short."""
        return self.quantity < 0

    @property
    def is_flat(self) -> bool:
        """Return True if position is flat."""
        return abs(self.quantity) < 1e-9

    @property
    def market_value(self) -> float:
        """Return current market value of position."""
        return abs(self.quantity) * self.current_price


@dataclass(frozen=True, slots=True)
class PortfolioState:
    """Snapshot of portfolio state at a point in time.

    Provides a complete view of portfolio including all positions,
    cash, and aggregate metrics. Immutable to ensure thread safety.

    Attributes:
        positions: Mapping of symbol to PositionState.
        cash: Available cash balance.
        equity: Total portfolio equity (cash + position values).
        peak_equity: Peak equity for drawdown calculation.
        margin_used: Total margin currently used.
        volatility: Portfolio volatility estimate.
        currency: Base currency.
        timestamp: When snapshot was taken.

    Raises:
        ValueError: If equity values are invalid.
    """

    positions: Mapping[str, PositionState] = field(default_factory=dict)
    cash: float = 0.0
    equity: float = 0.0
    peak_equity: float = 0.0
    margin_used: float = 0.0
    volatility: float = 0.0
    currency: str = "USD"
    timestamp: datetime = field(default_factory=_utc_now)

    def __post_init__(self) -> None:
        object.__setattr__(self, "positions", _freeze_mapping(self.positions))
        object.__setattr__(self, "timestamp", _ensure_utc(self.timestamp))

    @property
    def drawdown(self) -> float:
        """Calculate current drawdown from peak equity."""
        if self.peak_equity <= 0:
            return 0.0
        return max(0.0, (self.peak_equity - self.equity) / self.peak_equity)

    @property
    def net_exposure(self) -> float:
        """Calculate net exposure across all positions."""
        return sum(
            pos.quantity * pos.current_price for pos in self.positions.values()
        )

    @property
    def gross_exposure(self) -> float:
        """Calculate gross exposure across all positions."""
        return sum(
            abs(pos.quantity * pos.current_price) for pos in self.positions.values()
        )

    def position_for(self, symbol: str) -> PositionState | None:
        """Get position state for a symbol."""
        return self.positions.get(symbol)


# -----------------------------------------------------------------------------
# Strategy Signal & Context
# -----------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class StrategySignal:
    """Signal generated by a trading strategy.

    Represents a recommendation from a strategy about what action to take.
    Does not directly create orders - the decision loop processes signals
    through risk management before execution.

    Attributes:
        signal_id: Unique signal identifier.
        symbol: Instrument symbol.
        direction: Signal direction (long/short/flat).
        strength: Signal strength in range [0, 1].
        confidence: Confidence in signal in range [0, 1].
        strategy_id: ID of strategy that generated this signal.
        issued_at: When signal was issued.
        valid_until: When signal expires (None for no expiry).
        target_position: Target position size (normalized, -1 to 1).
        rationale: Human-readable explanation.
        metadata: Additional signal metadata.

    Raises:
        ValueError: If strength or confidence is out of range.
    """

    signal_id: SignalId
    symbol: str
    direction: SignalDirection
    strength: float = 1.0
    confidence: float = 1.0
    strategy_id: StrategyId | None = None
    issued_at: datetime = field(default_factory=_utc_now)
    valid_until: datetime | None = None
    target_position: float = 0.0
    rationale: str | None = None
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("symbol must be provided")
        if not 0.0 <= self.strength <= 1.0:
            raise ValueError("strength must be between 0 and 1")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("confidence must be between 0 and 1")
        if not -1.0 <= self.target_position <= 1.0:
            raise ValueError("target_position must be between -1 and 1")
        object.__setattr__(self, "metadata", _freeze_mapping(self.metadata))
        object.__setattr__(self, "issued_at", _ensure_utc(self.issued_at))
        if self.valid_until is not None:
            object.__setattr__(self, "valid_until", _ensure_utc(self.valid_until))

    @property
    def is_expired(self) -> bool:
        """Check if signal has expired."""
        if self.valid_until is None:
            return False
        return _utc_now() > self.valid_until


@dataclass(frozen=True, slots=True)
class MarketDataSnapshot:
    """Snapshot of market data for strategy context.

    Provides current market state including prices, volumes, and
    derived indicators to strategies for decision making.

    Attributes:
        symbol: Instrument symbol.
        bid: Best bid price.
        ask: Best ask price.
        last: Last trade price.
        volume: Current period volume.
        timestamp: When data was captured.
        ohlc: OHLC data if available (open, high, low, close).
        indicators: Pre-computed indicator values.
        metadata: Additional market metadata.
    """

    symbol: str
    bid: float = 0.0
    ask: float = 0.0
    last: float = 0.0
    volume: float = 0.0
    timestamp: datetime = field(default_factory=_utc_now)
    ohlc: Mapping[str, float] = field(default_factory=dict)
    indicators: Mapping[str, float] = field(default_factory=dict)
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "ohlc", _freeze_mapping(self.ohlc))
        object.__setattr__(self, "indicators", _freeze_mapping(self.indicators))
        object.__setattr__(self, "metadata", _freeze_mapping(self.metadata))
        object.__setattr__(self, "timestamp", _ensure_utc(self.timestamp))

    @property
    def mid(self) -> float:
        """Calculate mid price from bid/ask."""
        if self.bid > 0 and self.ask > 0:
            return (self.bid + self.ask) / 2.0
        return self.last

    @property
    def spread(self) -> float:
        """Calculate bid-ask spread."""
        if self.bid > 0 and self.ask > 0:
            return self.ask - self.bid
        return 0.0


@dataclass(frozen=True, slots=True)
class StrategyContext:
    """Context provided to strategies for decision making.

    Aggregates all information a strategy needs to generate signals:
    current portfolio state, market data, and operational mode.

    Attributes:
        mode: Current environment mode (backtest/paper/live).
        portfolio: Current portfolio state.
        market_data: Mapping of symbol to market data snapshot.
        timestamp: Current evaluation timestamp.
        metadata: Additional context metadata.
    """

    mode: EnvironmentMode
    portfolio: PortfolioState
    market_data: Mapping[str, MarketDataSnapshot] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=_utc_now)
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        object.__setattr__(self, "market_data", _freeze_mapping(self.market_data))
        object.__setattr__(self, "metadata", _freeze_mapping(self.metadata))
        object.__setattr__(self, "timestamp", _ensure_utc(self.timestamp))

    def get_market_data(self, symbol: str) -> MarketDataSnapshot | None:
        """Get market data for a symbol."""
        return self.market_data.get(symbol)

    def get_position(self, symbol: str) -> PositionState | None:
        """Get current position for a symbol."""
        return self.portfolio.position_for(symbol)


# -----------------------------------------------------------------------------
# Action Decision
# -----------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class ActionDecision:
    """Decision about what action the system should take.

    Represents the output of the decision loop after processing
    strategy signals through risk management. Immutable to ensure
    audit trail integrity.

    Attributes:
        action_id: Unique action identifier.
        action_type: Type of action to take.
        symbol: Instrument symbol.
        quantity: Action quantity.
        price: Target price (for limit orders).
        signal_id: Source signal that triggered this decision.
        strategy_id: Strategy that generated the source signal.
        confidence: Confidence in the decision.
        risk_score: Risk assessment score.
        rationale: Explanation for the decision.
        decided_at: When decision was made.
        metadata: Additional decision metadata.

    Raises:
        ValueError: If quantity is negative.
    """

    action_id: str
    action_type: ActionType
    symbol: str
    quantity: float = 0.0
    price: float | None = None
    signal_id: SignalId | None = None
    strategy_id: StrategyId | None = None
    confidence: float = 1.0
    risk_score: float = 0.0
    rationale: str | None = None
    decided_at: datetime = field(default_factory=_utc_now)
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.symbol:
            raise ValueError("symbol must be provided")
        if self.quantity < 0:
            raise ValueError("quantity cannot be negative")
        if self.price is not None and self.price <= 0:
            raise ValueError("price must be positive when provided")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError("confidence must be between 0 and 1")
        object.__setattr__(self, "metadata", _freeze_mapping(self.metadata))
        object.__setattr__(self, "decided_at", _ensure_utc(self.decided_at))

    @property
    def is_entry(self) -> bool:
        """Return True if action is an entry (buy/sell/scale_in)."""
        return self.action_type in (ActionType.BUY, ActionType.SELL, ActionType.SCALE_IN)

    @property
    def is_exit(self) -> bool:
        """Return True if action is an exit (close/reduce/scale_out)."""
        return self.action_type in (
            ActionType.CLOSE,
            ActionType.REDUCE,
            ActionType.SCALE_OUT,
        )


# -----------------------------------------------------------------------------
# AAR Event (Acceptor of Action Result)
# -----------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class AAREvent:
    """Acceptor of Action Result event for feedback loop.

    Captures the outcome of an action for learning and adaptation.
    Used to compute prediction errors and drive controller updates.

    Attributes:
        action_id: ID of the action this event relates to.
        prediction: Predicted outcome.
        outcome: Actual outcome.
        error: Computed prediction error.
        error_sign: Direction of error (+1 better, -1 worse, 0 equal).
        error_magnitude: Normalized magnitude of error.
        strategy_id: Strategy that initiated the action.
        timestamp: When the outcome was recorded.
        context_snapshot: System state at action time.
        metadata: Additional event metadata.
    """

    action_id: str
    prediction: float = 0.0
    outcome: float = 0.0
    error: float = 0.0
    error_sign: int = 0
    error_magnitude: float = 0.0
    strategy_id: StrategyId | None = None
    timestamp: datetime = field(default_factory=_utc_now)
    context_snapshot: Mapping[str, Any] = field(default_factory=dict)
    metadata: Mapping[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.error_sign not in (-1, 0, 1):
            raise ValueError("error_sign must be -1, 0, or 1")
        if self.error_magnitude < 0:
            raise ValueError("error_magnitude cannot be negative")
        object.__setattr__(
            self, "context_snapshot", _freeze_mapping(self.context_snapshot)
        )
        object.__setattr__(self, "metadata", _freeze_mapping(self.metadata))
        object.__setattr__(self, "timestamp", _ensure_utc(self.timestamp))

    @classmethod
    def from_prediction_outcome(
        cls,
        action_id: str,
        prediction: float,
        outcome: float,
        *,
        strategy_id: StrategyId | None = None,
        scale: float = 1.0,
        context_snapshot: Mapping[str, Any] | None = None,
    ) -> "AAREvent":
        """Create AAR event from prediction and outcome values.

        Computes error metrics based on the difference between
        predicted and actual outcomes.

        Args:
            action_id: ID of the action.
            prediction: Predicted value.
            outcome: Actual value.
            strategy_id: Strategy that initiated the action.
            scale: Scale factor for normalization.
            context_snapshot: System state at action time.

        Returns:
            AAREvent with computed error metrics.
        """
        raw_error = outcome - prediction
        abs_error = abs(raw_error)

        # Determine error sign (positive = outcome better than prediction)
        if abs_error < 1e-9:
            error_sign = 0
        elif raw_error > 0:
            error_sign = 1  # outcome > prediction = better
        else:
            error_sign = -1  # outcome < prediction = worse

        # Normalize error magnitude using tanh scaling
        import math

        safe_scale = max(abs(scale), 1e-9)
        error_magnitude = abs(math.tanh(raw_error / safe_scale))

        return cls(
            action_id=action_id,
            prediction=prediction,
            outcome=outcome,
            error=raw_error,
            error_sign=error_sign,
            error_magnitude=error_magnitude,
            strategy_id=strategy_id,
            context_snapshot=context_snapshot or {},
        )


# -----------------------------------------------------------------------------
# Exports
# -----------------------------------------------------------------------------

__all__ = [
    # Type aliases
    "OrderId",
    "StrategyId",
    "TradeId",
    "SignalId",
    "PositionId",
    # ID generators
    "generate_order_id",
    "generate_trade_id",
    "generate_signal_id",
    # Enums
    "EnvironmentMode",
    "ActionType",
    "SignalDirection",
    "OrderRequestType",
    "ExecutionStatus",
    # Order entities
    "OrderRequest",
    "OrderExecution",
    "Trade",
    # Position/Portfolio entities
    "PositionState",
    "PortfolioState",
    # Strategy entities
    "StrategySignal",
    "StrategyContext",
    "MarketDataSnapshot",
    # Decision entities
    "ActionDecision",
    # AAR entities
    "AAREvent",
]
