from __future__ import annotations

import argparse
import importlib
import json
import sys
from contextlib import contextmanager
from pathlib import Path
from typing import Dict

REPO_ROOT = Path(__file__).resolve().parents[2]
ORIGINAL_SYS_PATH = list(sys.path)
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from tools.audit.serotonin_test_stats import collect_serotonin_stats
from tools.audit.thermo_test_stats import collect_thermo_stats

sys.path[:] = ORIGINAL_SYS_PATH

ALLOWED_VERSION_MODULES = {
    "tradepulse.core.neuro.serotonin",
    "runtime.thermo_config",
}


@contextmanager
def _temp_sys_path(base_dir: Path) -> None:
    original = list(sys.path)
    sys.path.insert(0, str(base_dir / "src"))
    sys.path.insert(0, str(base_dir))
    try:
        yield
    finally:
        sys.path[:] = original


def _load_version(
    module_path: str, attribute: str = "__version__", base_dir: Path | None = None
) -> str:
    if module_path not in ALLOWED_VERSION_MODULES:
        raise ValueError(f"Unsupported module requested for version lookup: {module_path}")
    if base_dir is None:
        module = importlib.import_module(module_path)
        return getattr(module, attribute, "unknown")

    with _temp_sys_path(base_dir):
        module = importlib.import_module(module_path)
        return getattr(module, attribute, "unknown")


def _render_stats(title: str, stats: Dict[str, object], version: str) -> str:
    lines = [
        f"# {title}",
        "",
        f"- Version: `{version}`",
        f"- Collected tests: {stats['collected_tests_count']}",
        f"- Last collection timestamp: {stats['last_run_timestamp']}",
        "- Test files:",
    ]
    files = stats.get("test_files") or []
    if files:
        for path in files:
            lines.append(f"  - `{path}`")
    else:
        lines.append("  - _no matching test files discovered_")
    lines.append("")
    lines.append("_Generated by tools/audit/render_stats_md.py_")
    lines.append("")
    return "\n".join(lines)


def generate(base_dir: Path | None, output_dir: Path) -> None:
    root = base_dir if base_dir is not None else Path(__file__).resolve().parents[2]
    output_dir.mkdir(parents=True, exist_ok=True)

    serotonin_stats = collect_serotonin_stats(root)
    thermo_stats = collect_thermo_stats(root)

    serotonin_version = _load_version(
        "tradepulse.core.neuro.serotonin", base_dir=root
    )
    thermo_version = _load_version("runtime.thermo_config", base_dir=root)

    (output_dir / "serotonin_stats.md").write_text(
        _render_stats("Serotonin Controller Test Stats", serotonin_stats, serotonin_version),
        encoding="utf-8",
    )
    (output_dir / "thermo_stats.md").write_text(
        _render_stats("Thermodynamics Test Stats", thermo_stats, thermo_version),
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Render markdown summaries from serotonin and thermodynamics test stats."
    )
    parser.add_argument(
        "--base-dir",
        type=Path,
        help="Base repository directory (defaults to repository root).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("docs/_generated"),
        help="Output directory for generated markdown files.",
    )
    args = parser.parse_args()

    generate(args.base_dir, args.output_dir)


if __name__ == "__main__":
    main()
