#!/usr/bin/env python3
# Copyright (c) 2023-2026 Yaroslav Vasylenko (neuron7xLab)
# SPDX-License-Identifier: MIT
"""Render project status surfaces FROM the state ontology (GOV-005).

Single-source generation: this script reads ONLY
``governance/project_state.yaml`` and renders a status badge and a Markdown
status surface. It never hand-copies status wording — the SSOT is the sole
input, which is what makes contradiction between a badge and the ontology
impossible by construction.

Usage::

    python scripts/ci/gen_status_surfaces.py                 # full markdown -> stdout
    python scripts/ci/gen_status_surfaces.py --format badge  # badge line -> stdout
    python scripts/ci/gen_status_surfaces.py --out generated/PROJECT_STATUS.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
STATE_FILE = ROOT / "governance/project_state.yaml"


def load_state(path: Path = STATE_FILE) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: top level must be a mapping")
    return data


def render_badge(state: dict[str, Any]) -> str:
    surface = state.get("status_surface", {})
    current = state["current_state"]
    label = surface.get("badge_label", "maturity")
    color = surface.get("badge_color_by_rank", {}).get(current, "lightgrey")
    slug = current.replace("_", "__").replace("-", "--")
    url = f"https://img.shields.io/badge/{label}-{slug}-{color}"
    return f"![{label}: {current}]({url})"


def render_markdown(state: dict[str, Any]) -> str:
    surface = state.get("status_surface", {})
    project = surface.get("project", "project")
    current = state["current_state"]
    states = sorted(state["maturity_states"], key=lambda s: s["rank"])
    classes = sorted(state["evidence_classes"], key=lambda c: -int(c.get("strength", 0)))

    lines: list[str] = []
    lines.append("<!-- GENERATED by scripts/ci/gen_status_surfaces.py from")
    lines.append("     governance/project_state.yaml — DO NOT EDIT BY HAND. -->")
    lines.append(f"# {project} — Project Status")
    lines.append("")
    lines.append(render_badge(state))
    lines.append("")
    lines.append(f"**Current maturity state:** `{current}`")
    lines.append("")
    if surface.get("boundary_note"):
        lines.append(f"> {surface['boundary_note'].strip()}")
        lines.append("")

    lines.append("## Maturity ladder")
    lines.append("")
    lines.append("| Rank | State | Definition |")
    lines.append("| --- | --- | --- |")
    for s in states:
        marker = " **← current**" if s["name"] == current else ""
        definition = " ".join(str(s["definition"]).split())
        lines.append(f"| {s['rank']} | `{s['name']}`{marker} | {definition} |")
    lines.append("")

    lines.append("## Evidence classes")
    lines.append("")
    lines.append("| Class | Strength | Definition |")
    lines.append("| --- | --- | --- |")
    for c in classes:
        definition = " ".join(str(c["definition"]).split())
        lines.append(f"| `{c['name']}` | {c.get('strength', '')} | {definition} |")
    lines.append("")

    lines.append("## Claim-word firewall")
    lines.append("")
    lines.append("These status words are inadmissible unless the surrounding claim")
    lines.append("declares one of the required evidence classes. Enforced by")
    lines.append("`scripts/ci/check_state_ontology.py`.")
    lines.append("")
    lines.append("| Claim word | Required evidence class |")
    lines.append("| --- | --- |")
    for entry in state["forbidden_claims"]:
        requires = ", ".join(f"`{r}`" for r in entry["requires"])
        lines.append(f"| `{entry['claim']}` | {requires} |")
    lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render status surfaces from the state ontology.")
    parser.add_argument("--format", choices=("markdown", "badge"), default="markdown")
    parser.add_argument("--state-file", type=str, default=None, help="Override SSOT path.")
    parser.add_argument("--out", type=str, default=None, help="Write to a file instead of stdout.")
    args = parser.parse_args(argv)

    state_path = Path(args.state_file) if args.state_file else STATE_FILE
    state = load_state(state_path)

    rendered = render_badge(state) + "\n" if args.format == "badge" else render_markdown(state)

    if args.out:
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(rendered, encoding="utf-8")
        print(f"wrote {out_path}")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
